name: Update Blog Posts
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual runs
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://token-auth-access-vs-refresh.hashnode.dev/rss.xml"
      - name: Commit changes
        run: |
          git config --global user.name 'Monish Patel'
          git config --global user.email 'monishpatel831@gmail.com'
          git commit -am "📚 Update blog posts" || true
          git push
