name: Update Blog Posts
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual runs

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Required to push changes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for proper git history

      - name: Update README with blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://monish0210.hashnode.dev/rss.xml"  # Use your actual blog URL
          max_post_count: 5     # Limits to 5 latest posts
          commit_message: ""    # Disable auto-commit from the action
          readme_only: true     # Only update README.md

      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name 'Monish Patel'
          git config --global user.email 'monishpatel831@gmail.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "📚 Auto-update blog posts [skip ci]"
          git push
